# Generated by Django 4.2.0

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='日志级别')),
                ('log_type', models.CharField(choices=[('SYSTEM', '系统日志'), ('DETECTION', '检测日志'), ('ALERT', '报警日志'), ('USER', '用户操作日志'), ('ERROR', '错误日志')], default='SYSTEM', max_length=20, verbose_name='日志类型')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='模块')),
                ('function', models.CharField(blank=True, max_length=100, null=True, verbose_name='函数')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='行号')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='附加数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志条目',
                'verbose_name_plural': '日志条目',
                'db_table': 'log_entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp'], name='log_entries_timesta_b7e0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['level'], name='log_entries_level_8b7c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['log_type'], name='log_entries_log_typ_4a5c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'level'], name='log_entries_timesta_level_9f2a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'log_type'], name='log_entries_timesta_log_typ_7e3d4c_idx'),
        ),
    ]