# Generated by Django 5.2.7 on 2026-03-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="logentry",
            new_name="log_entries_timesta_93910a_idx",
            old_name="log_entries_timesta_b7e0e4_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="log_entries_level_c2561b_idx",
            old_name="log_entries_level_8b7c8e_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="log_entries_log_typ_10a642_idx",
            old_name="log_entries_log_typ_4a5c8d_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="log_entries_timesta_8b162d_idx",
            old_name="log_entries_timesta_level_9f2a1b_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="log_entries_timesta_ba4770_idx",
            old_name="log_entries_timesta_log_typ_7e3d4c_idx",
        ),
    ]
