# Generated by Django 4.2.0

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True, verbose_name='摄像头ID')),
                ('name', models.CharField(max_length=100, verbose_name='摄像头名称')),
                ('location', models.CharField(max_length=100, verbose_name='安装位置')),
                ('rtsp_url', models.URLField(blank=True, null=True, verbose_name='RTSP地址')),
                ('resolution_width', models.IntegerField(default=1920, verbose_name='分辨率宽度')),
                ('resolution_height', models.IntegerField(default=1080, verbose_name='分辨率高度')),
                ('fps', models.IntegerField(default=30, verbose_name='帧率')),
                ('detection_zones', models.JSONField(blank=True, default=list, verbose_name='检测区域')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('calibration_data', models.JSONField(blank=True, default=dict, verbose_name='标定数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摄像头配置',
                'verbose_name_plural': '摄像头配置',
                'db_table': 'camera_configurations',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DetectionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='阈值名称')),
                ('detection_type', models.CharField(max_length=50, verbose_name='检测类型')),
                ('confidence_threshold', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度阈值')),
                ('time_threshold_seconds', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='时间阈值(秒)')),
                ('distance_threshold_meters', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='距离阈值(米)')),
                ('additional_params', models.JSONField(blank=True, default=dict, verbose_name='附加参数')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '检测阈值',
                'verbose_name_plural': '检测阈值',
                'db_table': 'detection_thresholds',
                'ordering': ['detection_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('category', models.CharField(choices=[('detection', '检测配置'), ('alert', '报警配置'), ('video', '视频配置'), ('notification', '通知配置'), ('performance', '性能配置'), ('system', '系统配置')], max_length=20, verbose_name='配置分类')),
                ('config_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('float', '浮点数'), ('boolean', '布尔值'), ('json', 'JSON对象')], max_length=20, verbose_name='配置类型')),
                ('value', models.TextField(verbose_name='配置值')),
                ('default_value', models.TextField(verbose_name='默认值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='验证规则')),
                ('is_editable', models.BooleanField(default=True, verbose_name='可编辑')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='需要重启')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configurations',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.TextField(verbose_name='旧值')),
                ('new_value', models.TextField(verbose_name='新值')),
                ('changed_by', models.CharField(max_length=100, verbose_name='修改人')),
                ('change_reason', models.TextField(blank=True, verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='configuration.systemconfiguration', verbose_name='配置项')),
            ],
            options={
                'verbose_name': '配置变更历史',
                'verbose_name_plural': '配置变更历史',
                'db_table': 'configuration_history',
                'ordering': ['-created_at'],
            },
        ),
    ]