# Generated by Django 4.2.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('fall', '跌倒报警'), ('unattended_stove', '无人看管灶台'), ('system_error', '系统错误'), ('camera_offline', '摄像头离线')], max_length=20, verbose_name='报警类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=10, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('active', '活跃'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('false_positive', '误报')], default='active', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('camera_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='摄像头ID')),
                ('detection_confidence', models.FloatField(default=0.0, verbose_name='检测置信度')),
                ('video_clip_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='视频片段路径')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='截图路径')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='确认人')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='解决人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='解决备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报警记录',
                'verbose_name_plural': '报警记录',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('alert_type', models.CharField(choices=[('fall', '跌倒报警'), ('unattended_stove', '无人看管灶台'), ('system_error', '系统错误'), ('camera_offline', '摄像头离线')], max_length=20, verbose_name='报警类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('threshold_config', models.JSONField(default=dict, verbose_name='阈值配置')),
                ('notification_config', models.JSONField(default=dict, verbose_name='通知配置')),
                ('cooldown_seconds', models.IntegerField(default=60, verbose_name='冷却时间(秒)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报警规则',
                'verbose_name_plural': '报警规则',
                'db_table': 'alert_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', '邮件'), ('sms', '短信'), ('webhook', 'Webhook'), ('sound', '声音')], max_length=20, verbose_name='通知渠道')),
                ('recipient', models.CharField(max_length=200, verbose_name='接收者')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('retry', '重试中')], default='pending', max_length=20, verbose_name='发送状态')),
                ('message_content', models.TextField(verbose_name='消息内容')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert', verbose_name='关联报警')),
            ],
            options={
                'verbose_name': '通知日志',
                'verbose_name_plural': '通知日志',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'created_at'], name='alerts_alert_t_created_a_8f2c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='alerts_status_created_a_9e4b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='alerts_severit_created_a_7a3e5c_idx'),
        ),
    ]