# Generated by Django 5.2.7 on 2026-03-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_alert_t_28b6d7_idx",
            old_name="alerts_alert_t_created_a_8f2c1d_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_status_dc9bed_idx",
            old_name="alerts_status_created_a_9e4b2f_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="alerts_severit_1c615e_idx",
            old_name="alerts_severit_created_a_7a3e5c_idx",
        ),
    ]
